### PR TITLE
using -am option instead of -a when  execution linux "touch" command.…

### PR DESCRIPTION
**Pull request by Levon770**
… Current version will change only the access time. Changing it into -am will change access time and file modify time.

### CODE REVIEW

**Comment by ashleyw** [comment]
@Levon770 Thank you! Works great for my NFS + BindFS -> Docker setup! 🎉

For anyone searching until this gets merged:

```bash
git clone https://github.com/Levon770/vagrant-fsnotify && cd vagrant-fsnotify
rake build
# outputs: vagrant-fsnotify-0.3.0.gem
vagrant plugin install vagrant-fsnotify-0.3.0.gem
```

(I also removed the `gem "vagrant"` section from the `Gemfile` since it complained about my version of bundler being too high.)

**Comment by adrienkohlbecker** [comment]
Hi @Levon770 !
Thanks for taking the time to contribute. 
Before I merge this, would you mind sharing more details about why it is needed, as it isn't clear from the PR description?

**Comment by adrienkohlbecker** [comment]
This seems related to https://github.com/adrienkohlbecker/vagrant-fsnotify/issues/22
Would you mind changing to `touch` rather than `touch -am`?

**Comment by Levon770** [comment]
P

> Hi @Levon770 !
> Thanks for taking the time to contribute.
> Before I merge this, would you mind sharing more details about why it is needed, as it isn't clear from the PR description?

I am using Angular7,OS is update from Ubuntu 16.04 to Ubuntu 18.04. and Angulars ng serve did not trigger the recompile after update. even if execute the `touch -a _file_name_` in terminal. But Both `touch _file_name_` and `touch -am _file_name_` are triggering the file change in Angular. 

The -a param just change the access time, The idea to change the access time is great, but Ubuntu 18.04 broke this

**Comment by arayik-yervandyan** [comment]
@adrienkohlbecker  I think that from the architectural design part writing -am is more clear rather than -a. Because logically as @Levon770  said -a is just triggering access time, But Let's think actually we are modifying the file and also accessing to that file. So we need to show linux that file is accessed and also modified.  So my point of view is that we need to have -am there.

**Comment by adrienkohlbecker** [comment]
So neither `-a` nor `-m` will trigger a "file modified" event. Here is the sequence of events received by the guest when doing either `touch -a README.md` or `touch -m README.md`
```
$ inotifywait -r -m /vagrant
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/vagrant/ OPEN README.md
/vagrant/ ATTRIB README.md
/vagrant/ CLOSE_WRITE,CLOSE README.md
```

You can see it is only triggering an attribute change (as should be!). So a process listening only to `modified` events (eg. with `inotifywait -e MODIFY`) won't see either changes. I suspect most file watchers listen to something like `CLOSE` instead.

I'm guessing the issue here has more to do with something messing with atimes (such as the guest filesystem being mounted with `noatime`?) if adding `-m` fixes it.

For the record, here is the same command when editing a file on the guest directly (with `echo >> README.md`):
```
$ inotifywait -r -m /vagrant
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/vagrant/ OPEN README.md
/vagrant/ MODIFY README.md
/vagrant/ CLOSE_WRITE,CLOSE README.md
```

I would be wary of introducing race conditions if we were to change to something like `echo >> README.md`, but in any case if this solves your issue, let's merge it as is :-)

**Comment by adrienkohlbecker** [comment]
Version `0.3.1` is up on rubygems. Thanks again for contributing!

**Pull request merged**
