### PR TITLE
Add support for added and removed file events

### PR DESCRIPTION
**Pull request by leafac**
Tested by running inotifywait on the VM:

    sudo apt-get install inotify-tools
    inotifywait --monitor --recursive /vagrant

Fixes: https://github.com/adrienkohlbecker/vagrant-fsnotify/issues/2#issuecomment-116277594

### CODE REVIEW

**Comment by adrienkohlbecker** [comment]
LGTM, except for the use of case equality which I don't see the need for (lines `33` & `153`)

**Comment by leafac** [comment]
Hi, @adrienkohlbecker. Point taken, I fixed it.

Thanks for evaluating this PR.

**Comment by adrienkohlbecker** [comment]
Thanks, merging / releasing now

**Comment by adrienkohlbecker** [comment]
It's up on rubygems, thanks for your help :+1:

**Comment by leafac** [comment]
Brilliant. Thanks!

**Pull request merged**
